
# Définissez ici le nom de l’item ainsi que ses deux lignes de description.
# Set the item’s name, and its two description lines here.
item:
  name: "&9Pioche de Masse"
  lore1: "&7» &ePeut miner en 3x3, rapide et puissante."
  lore2: "&7» &c&oShift + clique droit pour configurer."


# Définissez ici les permissions pour les administrateurs et les joueurs
# Set the permissions for administrators and players here
permissions:
  admin: PDM.admin
  use: PDM.use
  message: "&c&oVous n'avez pas la permission."

# Définissez ici le prix d'une amélioration
# Set the price of an upgrade here
prix:
  price: 400
  message_ok: "&c$400 ont été retiré de votre compte."
  name_erreur: "&c&nErreur"
  message_erreur: "&c&oVous n'avez pas assez d'argent."

upgrade:
  name_lock: "&c&n"&c&nVerrouillé"
    lore:
  name_unlock: "&a&nDébloqué"
  name_off: "&6&nDésactivé"