command /givepioche:
    trigger:
        load yaml "plugins/Skript/scripts/Pioche de Masse/config.yml" as "config2"
        set {_perm} to yaml value "permissions.admin" from "config2"
        set {_erreur} to yaml value "permissions.message" from "config2"
        broadcast "%{_erreur}%"
        if player has permission "%{_perm}%":
            GivePiocheIndustrielle(player)
        else:
            send "%{_erreur}%"