command /givepioche <player>:
    trigger:


function Perm(p: player,p2: player):

    load yaml "plugins/Skript/scripts/Pioche de Masse/config.yml" as "config"
    set {_perm} to yaml value "permissions.admin" from "config"

    if {_p} has permission "%{_perm}%":
        GivePiocheIndustrielle({_p2})
    else:
        set {_message} to yaml value "permissions.message" from "config"
        send "%{_message}%" to {_p}

